
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox6;

	private global::Gtk.HBox hbox6;

	private global::Gtk.HBox hbox8;

	private global::Gtk.VBox vbox7;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Label Logo;

	private global::Gtk.Entry logoPathEntry;

	private global::Gtk.Button button5;

	private global::Gtk.HBox hbox11;

	private global::Gtk.Label label3;

	private global::Gtk.Entry filesEntry;

	private global::Gtk.Button button6;

	private global::Gtk.HBox hbox12;

	private global::Gtk.Label label4;

	private global::Gtk.Entry outputEntry;

	private global::Gtk.Button button7;

	private global::Gtk.VBox vbox8;

	private global::Gtk.HBox hbox13;

	private global::Gtk.Button button8;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.Logo = new global::Gtk.Label();
		this.Logo.Name = "Logo";
		this.Logo.LabelProp = global::Mono.Unix.Catalog.GetString("Logo");
		this.hbox10.Add(this.Logo);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.Logo]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.logoPathEntry = new global::Gtk.Entry();
		this.logoPathEntry.CanFocus = true;
		this.logoPathEntry.Name = "logoPathEntry";
		this.logoPathEntry.IsEditable = false;
		this.logoPathEntry.InvisibleChar = '•';
		this.hbox10.Add(this.logoPathEntry);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.logoPathEntry]));
		w2.Position = 1;
		// Container child hbox10.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("...");
		this.hbox10.Add(this.button5);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.button5]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox7.Add(this.hbox10);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox10]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Input files");
		this.hbox11.Add(this.label3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.label3]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.filesEntry = new global::Gtk.Entry();
		this.filesEntry.CanFocus = true;
		this.filesEntry.Name = "filesEntry";
		this.filesEntry.IsEditable = false;
		this.filesEntry.InvisibleChar = '•';
		this.hbox11.Add(this.filesEntry);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.filesEntry]));
		w6.Position = 1;
		// Container child hbox11.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("...");
		this.hbox11.Add(this.button6);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.button6]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox7.Add(this.hbox11);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox11]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Output folder");
		this.hbox12.Add(this.label4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.label4]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.outputEntry = new global::Gtk.Entry();
		this.outputEntry.CanFocus = true;
		this.outputEntry.Name = "outputEntry";
		this.outputEntry.IsEditable = false;
		this.outputEntry.InvisibleChar = '•';
		this.hbox12.Add(this.outputEntry);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.outputEntry]));
		w10.Position = 1;
		// Container child hbox12.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("...");
		this.hbox12.Add(this.button7);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.button7]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox7.Add(this.hbox12);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox12]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.hbox8.Add(this.vbox7);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.vbox7]));
		w13.Position = 0;
		this.hbox6.Add(this.hbox8);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.hbox8]));
		w14.Position = 0;
		this.vbox6.Add(this.hbox6);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox6]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.button8 = new global::Gtk.Button();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString("Start");
		this.hbox13.Add(this.button8);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.button8]));
		w16.Position = 0;
		this.vbox8.Add(this.hbox13);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox13]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		this.vbox6.Add(this.vbox8);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vbox8]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		this.Add(this.vbox6);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 429;
		this.DefaultHeight = 271;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button5.Clicked += new global::System.EventHandler(this.OnChooseLogo);
		this.button6.Clicked += new global::System.EventHandler(this.OnChooseFiles);
		this.button7.Clicked += new global::System.EventHandler(this.OnChooseOutput);
		this.button8.Clicked += new global::System.EventHandler(this.OnStart);
	}
}
